# --------------------------------------------------
# 数据预处理配置文件 (config.yaml)
# --------------------------------------------------

data:
  type: raw_signal
  # 原始 .mat 数据文件所在的目录路径
  data_path: 'data/matfiles'
  
  file_names:
    - 'normal_0.mat'     # 标签: 0
    - 'IR007_0.mat'      # 标签: 1
    - 'B007_0.mat'       # 标签: 2
    - 'OR007@6_0.mat'    # 标签: 3
    - 'IR014_0.mat'      # 标签: 4
    - 'B014_0.mat'       # 标签: 5
    - 'OR014@6_0.mat'    # 标签: 6
    - 'IR021_0.mat'      # 标签: 7
    - 'B021_0.mat'       # 标签: 8
    - 'OR021@6_0.mat'    # 标签: 9
  
  truncated_value: 102912
  time_steps: 1024
  overlap_ratio: 0.5
  
  csv_output_path: 'data/samples_data.csv'
  
  # --- make_raw_signal_dataset.py 配置 ---
  
  csv_file_path: 'data/samples_data.csv'
  split_ratios: [0.7, 0.2, 0.1]
  
  # 预处理原始信号输出目录
  raw_signal_output_dir: 'data/RawSignals'

# --------------------------------------------------
# 模型和训练配置文件
# --------------------------------------------------

model:
  # 模型类型: ResNet1d
  type: 'ResNet1d'
  num_classes: 10

train:
  num_epochs: 20
  
  batch_size: 32
  learning_rate: 0.01
  checkpoint_dir: 'checkpoints/ResNet1d/run1'
  notes: 'ResNet1d 测试'
  
  # 优化器配置
  optimizer: 'Adam'
  
  # 学习率调度器配置
  scheduler:
    use_scheduler: true
    scheduler_type: 'StepLR'
    step_size: 2
    gamma: 0.8

