# --------------------------------------------------
# 数据预处理配置文件 (config.yaml)
# --------------------------------------------------

data:
  type: image
  # 原始 .mat 数据文件所在的目录路径
  data_path: 'data/matfiles'
  
  # 当前顺序: 0:正常, 1-3:007尺寸(内圈/滚珠/外圈), 4-6:014尺寸(内圈/滚珠/外圈), 7-9:021尺寸(内圈/滚珠/外圈)
  file_names:
    - 'normal_0.mat'     # 标签: 0
    - 'IR007_0.mat'      # 标签: 1
    - 'B007_0.mat'       # 标签: 2
    - 'OR007@6_0.mat'    # 标签: 3
    - 'IR014_0.mat'      # 标签: 4
    - 'B014_0.mat'       # 标签: 5
    - 'OR014@6_0.mat'    # 标签: 6
    - 'IR021_0.mat'      # 标签: 7
    - 'B021_0.mat'       # 标签: 8
    - 'OR021@6_0.mat'    # 标签: 9
  
  # 从每个时间序列的开头截取的数据点数量
  truncated_value: 102912
  
  # 定义每个样本的长度
  time_steps: 1024
  
  # 定义相邻两个样本之间的重叠比例
  overlap_ratio: 0.5
  
  # 指定最终生成的 CSV 文件的存放路径和文件名
  csv_output_path: 'data/samples_data.csv'
  
  # --- make_img_dataset.py 配置 ---
  
  # 处理好的 samples_data.csv 文件路径
  csv_file_path: 'data/samples_data.csv'

  # 数据集划分比例 [训练集, 验证集, 测试集]
  split_ratios: [0.7, 0.2, 0.1]

  # 生成的时频图像的输出目录
  img_output_dir: 'data/STFTimages'

  # 生成图像的尺寸 (像素)
  image_size: 224

  # 原始信号的采样频率 (Hz)
  sampling_frequency: 12000

  # 短时傅里叶变换 (STFT) 的窗口大小
  stft_window_size: 64

  # 短时傅里叶变换 (STFT) 的窗口重叠率
  stft_overlap: 0.5

# --------------------------------------------------
# 模型和训练配置文件
# --------------------------------------------------

model:
  type: MyCNN
  # 分类的类别总数
  num_classes: 10
  # 模型名称
  name: 'MyCNN_CWRU'

train:
  # 训练的总轮次 (epochs)
  num_epochs: 50
  # 每个批次的大小 (batch_size)
  batch_size: 32
  # 优化器的学习率
  learning_rate: 0.0001
  
  # 优化器配置
  optimizer: 'Adam'
  
  # 保存模型权重和结果的目录
  checkpoint_dir: 'checkpoints/Handcraft_MYCNN/3layers_0.0001lr_Dropout_lr_scheduler'
  # 实验说明和笔记（可选，手动填写）
  notes: 'Handcraft MyCNN baseline'
  
  # 学习率调度器配置 (默认 StepLR)
  scheduler:
    use_scheduler: true
    scheduler_type: 'StepLR'
    step_size: 20
    gamma: 0.5
